name: Publish (PyPI)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag version (e.g. v1.3.2)"
        required: true
  release:
    types: [published]

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Build package
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }} 